export const FETCH_JOBS_START = "FETCH_JOBS_START";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILED = "FETCH_JOBS_FAILED";
export const FETCH_JOBS_PAGE = "FETCH_JOBS_PAGE";
