export const FETCH_JOBS_START = "FETCH_JOBS_START";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILED = "FETCH_JOBS_FAILED";
export const FETCH_JOBS_PAGE = "FETCH_JOBS_PAGE";
export const UPDATE_JOBS_LOCATION = "UPDATE_JOBS_LOCATION";
export const UPDATE_JOBS_FULLTIME = "UPDATE_JOBS_FULLTIME";
export const UPDATE_JOBS_DESCRIPTION = "UPDATE_JOBS_DESCRIPTION";
